### ISSUE TITLE
Adding a license to the repo?

### ISSUE THREAD

**Issue by hr-oss** [cgsdev0/GameOff2022#42]
Howdy!

Love this game :D I was curious, if you’d like to add a license to this repo? That way people don’t have to worry about getting sued if they use the code/make a branch etc😆

Here’s a tutorial on how to add one: https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-license-to-a-repository

Thank you !

**Comment by cgsdev0** [comment]
no.

**Comment by hr-oss** [comment]
Alrighty well I appreciate your looking into it anyways. Thanks and have a great day!
